import streamlit as st
import pandas as pd
import joblib

# Load trained model and scaler
model = joblib.load("final_disease_prediction_model.pkl")
scaler = joblib.load("final_scaler.pkl")

# Page configuration
st.set_page_config(
    page_title="Early Disease Prediction",
    page_icon="🩺",
    layout="centered"
)

# Title
st.title("🩺 Early Disease Prediction System")
st.write(
    "Enter the patient's health information below to get a machine learning prediction."
)

# Patient information
age = st.number_input(
    "Age",
    min_value=1,
    max_value=120,
    value=25
)

bmi = st.number_input(
    "BMI",
    min_value=10.0,
    max_value=60.0,
    value=22.5
)

blood_pressure = st.number_input(
    "Blood Pressure (mmHg)",
    min_value=50.0,
    max_value=250.0,
    value=120.0
)

cholesterol = st.number_input(
    "Cholesterol (mg/dL)",
    min_value=50.0,
    max_value=500.0,
    value=180.0
)

glucose = st.number_input(
    "Glucose (mg/dL)",
    min_value=40.0,
    max_value=500.0,
    value=100.0
)

heart_rate = st.number_input(
    "Heart Rate (bpm)",
    min_value=30.0,
    max_value=220.0,
    value=72.0
)

gender = st.selectbox(
    "Gender",
    ["Female", "Male"]
)

smoking = st.selectbox(
    "Smoking",
    ["No", "Yes"]
)

exercise = st.selectbox(
    "Exercise Level",
    ["Low", "Moderate", "High"]
)

# Prediction button
if st.button("🔍 Predict Disease"):

    # Create input data with exactly the same columns
    new_data = pd.DataFrame({
        "Age": [age],
        "BMI": [bmi],
        "Blood_Pressure_mmHg": [blood_pressure],
        "Cholesterol_mg_dL": [cholesterol],
        "Glucose_mg_dL": [glucose],
        "Heart_Rate_bpm": [heart_rate],
        "Gender_Male": [1 if gender == "Male" else 0],
        "Smoking_Yes": [1 if smoking == "Yes" else 0],
        "Exercise_Level_Low": [1 if exercise == "Low" else 0],
        "Exercise_Level_Moderate": [1 if exercise == "Moderate" else 0]
    })

    # Scale input
    new_data_scaled = scaler.transform(new_data)

    # Prediction
    prediction = model.predict(new_data_scaled)

    # Display result
    st.success(f"Predicted Disease: {prediction[0]}")

    st.info(
        "This prediction is generated by a machine learning model "
        "and is intended for educational/research purposes, not medical diagnosis."
    )